server:
  port: 8090

spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/aop_log?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mrx.aop.domains